import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import fs from 'fs';
import type { IncomingMessage, ServerResponse } from 'http';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SPRITE_KEYS = [
  'WALK_A', 'WALK_B', 'BLINK_A', 'BLINK_B',
  'SIT_A',  'SIT_B',  'LIE_A',  'LIE_B',
  'JUMP_1', 'JUMP_2', 'JUMP_3', 'JUMP_4',
  'DREAM',
] as const;

function generateSpritesTs(frames: Record<string, string[]>): string {
  const lines = [
    '// Auto-generated by dev/src/components/Studio.tsx — edit sprites in the browser, save with "Save sprites".',
    '',
    "export type SpriteKey =",
    "  | 'WALK_A' | 'WALK_B' | 'BLINK_A' | 'BLINK_B'",
    "  | 'SIT_A'  | 'SIT_B'  | 'LIE_A'  | 'LIE_B'",
    "  | 'JUMP_1' | 'JUMP_2' | 'JUMP_3' | 'JUMP_4'",
    "  | 'DREAM';",
    '',
    'export const RAW_SPRITES: Record<SpriteKey, string[]> = {',
  ];
  for (const key of SPRITE_KEYS) {
    const rows = frames[key];
    if (rows) {
      const pad = key.length < 7 ? ' '.repeat(7 - key.length) : '';
      const rowStrs = rows.map(r => `'${r}'`).join(', ');
      lines.push(`  ${key}:${pad} [${rowStrs}],`);
    }
  }
  lines.push('};', '');
  return lines.join('\n');
}

function saveSpritesPlugin(): Plugin {
  return {
    name: 'save-sprites',
    configureServer(server) {
      server.middlewares.use('/save-sprites', (req: IncomingMessage, res: ServerResponse) => {
        if (req.method !== 'POST') { res.writeHead(405); res.end(); return; }
        let body = '';
        req.on('data', (chunk: Buffer) => { body += chunk.toString(); });
        req.on('end', () => {
          try {
            const frames = JSON.parse(body) as Record<string, string[]>;
            const content = generateSpritesTs(frames);
            const spritesPath = resolve(__dirname, 'src/sprites.ts');
            fs.writeFileSync(spritesPath, content, 'utf8');
            console.log('[save-sprites] wrote', spritesPath);
            res.writeHead(200, { 'Content-Type': 'text/plain' });
            res.end('OK');
          } catch (e) {
            res.writeHead(400, { 'Content-Type': 'text/plain' });
            res.end(String(e));
          }
        });
      });
    },
  };
}

export default defineConfig({
  root: 'dev',
  plugins: [react(), saveSpritesPlugin()],
  resolve: {
    alias: {
      '@src': resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 8766,
  },
  build: {
    outDir: resolve(__dirname, 'dist-dev'),
    emptyOutDir: true,
  },
});
