import react from '@vitejs/plugin-react';
import fs from 'fs';
import type { IncomingMessage, ServerResponse } from 'http';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { defineConfig, type Plugin } from 'vite';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SPRITE_KEYS = [
  'WALK_A',
  'WALK_B',
  'BLINK_A',
  'BLINK_B',
  'SIT_A',
  'SIT_B',
  'LIE_A',
  'LIE_B',
  'JUMP_1',
  'JUMP_2',
  'JUMP_3',
  'JUMP_4',
  'DREAM',
  'BURP_A',
  'BURP_B',
  'POO_A',
  'POO_B',
] as const;

type PetBehavior = 'walk' | 'sit' | 'lie' | 'jump' | 'perch' | 'dream' | 'burp' | 'poo';

interface BehaviorChanceConfig {
  chance: number;
  minDuration: number;
  maxDuration: number;
}

interface BehaviorPeriodConfig {
  walkBudgetMin: number;
  walkBudgetMax: number;
  transitions: Partial<Record<PetBehavior, BehaviorChanceConfig>>;
}

interface PetBehaviorConfig {
  initialBlinkMin: number;
  initialBlinkMax: number;
  repeatBlinkMin: number;
  repeatBlinkMax: number;
  burpResidueTTL: number;
  pooResidueTTL: number;
  day: BehaviorPeriodConfig;
  night: BehaviorPeriodConfig;
}

const EDITABLE_BEHAVIORS: PetBehavior[] = ['sit', 'lie', 'jump', 'perch', 'dream', 'burp', 'poo'];

function generateSpritesTs(frames: Record<string, string[]>): string {
  const lines = [
    '// Auto-generated by dev/src/components/Studio.tsx — edit sprites in the browser, save with "Save sprites".',
    '',
    'export type SpriteKey =',
    "  | 'WALK_A'",
    "  | 'WALK_B'",
    "  | 'BLINK_A'",
    "  | 'BLINK_B'",
    "  | 'SIT_A'",
    "  | 'SIT_B'",
    "  | 'LIE_A'",
    "  | 'LIE_B'",
    "  | 'JUMP_1'",
    "  | 'JUMP_2'",
    "  | 'JUMP_3'",
    "  | 'JUMP_4'",
    "  | 'DREAM'",
    "  | 'BURP_A'",
    "  | 'BURP_B'",
    "  | 'POO_A'",
    "  | 'POO_B';",
    '',
    'export const RAW_SPRITES: Record<SpriteKey, string[]> = {',
  ];
  for (const key of SPRITE_KEYS) {
    const rows = frames[key];
    if (rows) {
      const rowStrs = rows.map((r) => `'${r}'`).join(', ');
      lines.push(`  ${key}: [${rowStrs}],`);
    }
  }
  lines.push('};', '');
  return lines.join('\n');
}

function generatePetConfigTs(config: PetBehaviorConfig): string {
  const lines = [
    '// Auto-generated by dev/src/components/Studio.tsx — edit behavior config in the browser, save with "Save all".',
    '',
    "import type { PetBehavior } from '../render/pet/types.js';",
    '',
    'export interface BehaviorChanceConfig {',
    '  chance: number;',
    '  minDuration: number;',
    '  maxDuration: number;',
    '}',
    '',
    'export interface BehaviorPeriodConfig {',
    '  walkBudgetMin: number;',
    '  walkBudgetMax: number;',
    '  transitions: Partial<Record<PetBehavior, BehaviorChanceConfig>>;',
    '}',
    '',
    'export interface PetBehaviorConfig {',
    '  initialBlinkMin: number;',
    '  initialBlinkMax: number;',
    '  repeatBlinkMin: number;',
    '  repeatBlinkMax: number;',
    '  burpResidueTTL: number;',
    '  pooResidueTTL: number;',
    '  day: BehaviorPeriodConfig;',
    '  night: BehaviorPeriodConfig;',
    '}',
    '',
    "export const EDITABLE_BEHAVIORS: PetBehavior[] = ['sit', 'lie', 'jump', 'perch', 'dream', 'burp', 'poo'];",
    '',
    'export const PET_BEHAVIOR_CONFIG: PetBehaviorConfig = {',
    `  initialBlinkMin: ${config.initialBlinkMin},`,
    `  initialBlinkMax: ${config.initialBlinkMax},`,
    `  repeatBlinkMin: ${config.repeatBlinkMin},`,
    `  repeatBlinkMax: ${config.repeatBlinkMax},`,
    `  burpResidueTTL: ${config.burpResidueTTL},`,
    `  pooResidueTTL: ${config.pooResidueTTL},`,
  ];

  for (const periodName of ['day', 'night'] as const) {
    const period = config[periodName];
    lines.push(`  ${periodName}: {`);
    lines.push(`    walkBudgetMin: ${period.walkBudgetMin},`);
    lines.push(`    walkBudgetMax: ${period.walkBudgetMax},`);
    lines.push('    transitions: {');
    for (const behavior of EDITABLE_BEHAVIORS) {
      const entry = period.transitions[behavior];
      if (!entry) continue;
      lines.push(`      ${behavior}: { chance: ${entry.chance}, minDuration: ${entry.minDuration}, maxDuration: ${entry.maxDuration} },`);
    }
    lines.push('    },');
    lines.push('  },');
  }

  lines.push('};', '');
  return lines.join('\n');
}

function saveSpritesPlugin(): Plugin {
  return {
    name: 'save-sprites',
    configureServer(server) {
      server.middlewares.use('/save-sprites', (req: IncomingMessage, res: ServerResponse) => {
        if (req.method !== 'POST') {
          res.writeHead(405);
          res.end();
          return;
        }
        let body = '';
        req.on('data', (chunk: Buffer) => {
          body += chunk.toString();
        });
        req.on('end', () => {
          try {
            const frames = JSON.parse(body) as Record<string, string[]>;
            const content = generateSpritesTs(frames);
            const spritesPath = resolve(__dirname, 'src/sprites.ts');
            fs.writeFileSync(spritesPath, content, 'utf8');
            console.log('[save-sprites] wrote', spritesPath);
            res.writeHead(200, { 'Content-Type': 'text/plain' });
            res.end('OK');
          } catch (e) {
            res.writeHead(400, { 'Content-Type': 'text/plain' });
            res.end(String(e));
          }
        });
      });
    },
  };
}

function savePetConfigPlugin(): Plugin {
  return {
    name: 'save-pet-config',
    configureServer(server) {
      server.middlewares.use('/save-pet-config', (req: IncomingMessage, res: ServerResponse) => {
        if (req.method !== 'POST') {
          res.writeHead(405);
          res.end();
          return;
        }
        let body = '';
        req.on('data', (chunk: Buffer) => {
          body += chunk.toString();
        });
        req.on('end', () => {
          try {
            const config = JSON.parse(body) as PetBehaviorConfig;
            const content = generatePetConfigTs(config);
            const configPath = resolve(__dirname, 'src/pet/config.ts');
            fs.writeFileSync(configPath, content, 'utf8');
            console.log('[save-pet-config] wrote', configPath);
            res.writeHead(200, { 'Content-Type': 'text/plain' });
            res.end('OK');
          } catch (e) {
            res.writeHead(400, { 'Content-Type': 'text/plain' });
            res.end(String(e));
          }
        });
      });
    },
  };
}

export default defineConfig({
  root: 'dev',
  plugins: [react(), saveSpritesPlugin(), savePetConfigPlugin()],
  resolve: {
    alias: {
      '@src': resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 8766,
  },
  build: {
    outDir: resolve(__dirname, 'dist-dev'),
    emptyOutDir: true,
  },
});
