import * as esbuild from "esbuild";
import * as http from "node:http";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SPRITES_PATH = path.resolve(__dirname, "../src/sprites.ts");
const SAVE_PORT = 8767;

const FRAME_KEYS = [
  'WALK_A','WALK_B','BLINK_A','BLINK_B',
  'SIT_A','SIT_B','LIE_A','LIE_B',
  'JUMP_1','JUMP_2','JUMP_3','JUMP_4',
  'DREAM',
];

function generateSpritesTs(frames) {
  const lines = [
    "// Auto-generated by dev/studio.html — edit sprites in the browser, save with \"Save sprites\".",
    "",
    "export type SpriteKey =",
    "  | 'WALK_A' | 'WALK_B' | 'BLINK_A' | 'BLINK_B'",
    "  | 'SIT_A'  | 'SIT_B'  | 'LIE_A'  | 'LIE_B'",
    "  | 'JUMP_1' | 'JUMP_2' | 'JUMP_3' | 'JUMP_4'",
    "  | 'DREAM';",
    "",
    "export const RAW_SPRITES: Record<SpriteKey, string[]> = {",
  ];
  for (const key of FRAME_KEYS) {
    const rows = frames[key];
    if (rows) {
      const pad = key.length < 7 ? ' '.repeat(7 - key.length) : '';
      const rowStrs = rows.map(r => "'" + r + "'").join(', ');
      lines.push(`  ${key}:${pad} [${rowStrs}],`);
    }
  }
  lines.push("};", "");
  return lines.join("\n");
}

// ---- Save endpoint ----
const saveServer = http.createServer((req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    res.writeHead(204); res.end(); return;
  }

  if (req.method === "POST" && req.url === "/save-sprites") {
    let body = "";
    req.on("data", chunk => { body += chunk; });
    req.on("end", () => {
      try {
        const frames = JSON.parse(body);
        const content = generateSpritesTs(frames);
        fs.writeFileSync(SPRITES_PATH, content, "utf8");
        res.writeHead(200, { "Content-Type": "text/plain" });
        res.end("OK");
        console.log("Sprites saved →", path.relative(process.cwd(), SPRITES_PATH));
      } catch (e) {
        res.writeHead(400, { "Content-Type": "text/plain" });
        res.end(String(e));
      }
    });
    return;
  }

  res.writeHead(404); res.end("Not found");
});

saveServer.listen(SAVE_PORT, "127.0.0.1", () => {
  console.log(`Save endpoint  → http://localhost:${SAVE_PORT}/save-sprites`);
});

// ---- esbuild watch + serve ----
const ctx = await esbuild.context({
  entryPoints: ["src/browser-bundle.ts"],
  bundle: true,
  format: "iife",
  globalName: "SimLib",
  outfile: "dev/render.js",
  banner: {
    js: `new EventSource('/esbuild').addEventListener('change', () => location.reload());`,
  },
});

await ctx.watch();
const { port } = await ctx.serve({ servedir: "dev", port: 8766 });
console.log(`Simulator      → http://localhost:${port}/simulator.html`);
console.log(`Studio         → http://localhost:${port}/studio.html`);
