// Auto-generated by dev/src/components/Studio.tsx — edit behavior config in the browser, save with "Save all".

import type { PetBehavior } from '../render/pet/types.js';

export interface BehaviorChanceConfig {
  chance: number;
  minDuration: number;
  maxDuration: number;
}

export interface BehaviorPeriodConfig {
  walkBudgetMin: number;
  walkBudgetMax: number;
  transitions: Partial<Record<PetBehavior, BehaviorChanceConfig>>;
}

export interface PetBehaviorConfig {
  initialBlinkMin: number;
  initialBlinkMax: number;
  repeatBlinkMin: number;
  repeatBlinkMax: number;
  burpResidueTTL: number;
  pooResidueTTL: number;
  day: BehaviorPeriodConfig;
  night: BehaviorPeriodConfig;
}

export const EDITABLE_BEHAVIORS: PetBehavior[] = ['sit', 'lie', 'jump', 'perch', 'dream', 'burp', 'poo'];

export const PET_BEHAVIOR_CONFIG: PetBehaviorConfig = {
  initialBlinkMin: 20,
  initialBlinkMax: 40,
  repeatBlinkMin: 25,
  repeatBlinkMax: 50,
  burpResidueTTL: 1000,
  pooResidueTTL: 1000,
  day: {
    walkBudgetMin: 15,
    walkBudgetMax: 40,
    transitions: {
      sit: { chance: 0.15, minDuration: 30, maxDuration: 80 },
      lie: { chance: 0.08, minDuration: 50, maxDuration: 120 },
      jump: { chance: 0.06, minDuration: 8, maxDuration: 8 },
      perch: { chance: 0.18, minDuration: 8, maxDuration: 16 },
      dream: { chance: 0, minDuration: 120, maxDuration: 120 },
      burp: { chance: 0.04, minDuration: 10, maxDuration: 14 },
      poo: { chance: 0.02, minDuration: 8, maxDuration: 10 },
    },
  },
  night: {
    walkBudgetMin: 3,
    walkBudgetMax: 10,
    transitions: {
      sit: { chance: 0.08, minDuration: 20, maxDuration: 50 },
      lie: { chance: 0.2, minDuration: 60, maxDuration: 120 },
      jump: { chance: 0, minDuration: 8, maxDuration: 8 },
      perch: { chance: 0, minDuration: 8, maxDuration: 16 },
      dream: { chance: 0.5, minDuration: 100, maxDuration: 180 },
      burp: { chance: 0.02, minDuration: 10, maxDuration: 12 },
      poo: { chance: 0.01, minDuration: 8, maxDuration: 10 },
    },
  },
};
