// Auto-generated by dev/src/components/Studio.tsx — edit behavior config in the browser, save with "Save all".
import type { PetBehavior } from '../render/pet-draw.js';

export interface BehaviorChanceConfig {
  chance: number;
  minDuration: number;
  maxDuration: number;
}

export interface BehaviorPeriodConfig {
  walkBudgetMin: number;
  walkBudgetMax: number;
  transitions: Partial<Record<PetBehavior, BehaviorChanceConfig>>;
}

export interface PetBehaviorConfig {
  initialBlinkMin: number;
  initialBlinkMax: number;
  repeatBlinkMin: number;
  repeatBlinkMax: number;
  day: BehaviorPeriodConfig;
  night: BehaviorPeriodConfig;
}

export const EDITABLE_BEHAVIORS: PetBehavior[] = ['sit', 'lie', 'jump', 'perch', 'dream'];

export const PET_BEHAVIOR_CONFIG: PetBehaviorConfig = {
  initialBlinkMin: 20,
  initialBlinkMax: 40,
  repeatBlinkMin: 25,
  repeatBlinkMax: 50,
  day: {
    walkBudgetMin: 15,
    walkBudgetMax: 40,
    transitions: {
      sit: { chance: 0.15, minDuration: 30, maxDuration: 80 },
      lie: { chance: 0.1, minDuration: 50, maxDuration: 120 },
      jump: { chance: 0.1, minDuration: 8, maxDuration: 8 },
      perch: { chance: 0.5, minDuration: 8, maxDuration: 16 },
      dream: { chance: 0, minDuration: 120, maxDuration: 120 },
    },
  },
  night: {
    walkBudgetMin: 3,
    walkBudgetMax: 10,
    transitions: {
      sit: { chance: 0.15, minDuration: 20, maxDuration: 50 },
      lie: { chance: 0.2, minDuration: 50, maxDuration: 100 },
      jump: { chance: 0, minDuration: 8, maxDuration: 8 },
      perch: { chance: 0, minDuration: 8, maxDuration: 16 },
      dream: { chance: 0.55, minDuration: 80, maxDuration: 160 },
    },
  },
};
