// Auto-generated by dev/studio.html — edit sprites in the browser, save with "Save sprites".

export type SpriteKey =
  | 'WALK_A'
  | 'WALK_B'
  | 'BLINK_A'
  | 'BLINK_B'
  | 'SIT_A'
  | 'SIT_B'
  | 'LIE_A'
  | 'LIE_B'
  | 'JUMP_1'
  | 'JUMP_2'
  | 'JUMP_3'
  | 'JUMP_4'
  | 'DREAM';

export const RAW_SPRITES: Record<SpriteKey, string[]> = {
  WALK_A: ['..o.o', '..gog', '.oooo', '.r.r.'],
  WALK_B: ['..o.o', '..gog', '.oooo', '..rr.'],
  BLINK_A: ['..o.o', '..ooo', '.oooo', '.r.r.'],
  BLINK_B: ['..o.o', '..ooo', '.oooo', '..rr.'],
  SIT_A: ['..o.o', '..gog', '.sooo', '.ssr.'],
  SIT_B: ['..o.o', '..ooo', '.sooo', '.ssr.'],
  LIE_A: ['..o.o', '..gog', '.oooo'],
  LIE_B: ['..o.o', '..ooo', '.oooo'],
  JUMP_1: ['..o.o', '..gog', '.oooo', '.r.r.'],
  JUMP_2: ['..o.o', '..gog', '.oooo', '.o.o.'],
  JUMP_3: ['..o.o', '..gog', '.oooo', '.....'],
  JUMP_4: ['..o.o', '..gog', '.oooo', '.r.r.'],
  DREAM: ['.....', '..o.o', '.sooo', '.ssso'],
};
